Create LICENSE
linkml/prefixmaps pull request #20
Opened 2022-10-25 22:45 UTC by cmungall

Fixes #18

2022-10-25 22:50 UTC, cthoyt commented
Please also include this in the pyproject.toml as well

2022-10-25 22:57 UTC, kltm requested changes
Noting use of Apache 2.0, an open and permissive license with patent protection clauses.

2022-10-25 22:57 UTC, kltm commented on LICENSE
> +   Copyright [yyyy] [name of copyright owner]
Date an copyright holder needs to be filled out

2023-05-03 15:00 UTC, sierra-moxon commented
fixed according to reviews.

2023-05-03 15:01 UTC, sierra-moxon approved these changes

2023-05-03 17:54 UTC, caufieldjh approved these changes

2023-05-03 18:10 UTC, merged